### ISSUE TITLE
Error during autoscan

### ISSUE THREAD

**Issue by aptonline** [reloxx13/TasmoAdmin#107] opened 2018-05-24 16:23 UTC
Docker install on Synology.

On first running of autoscan I receive the following errors inline:

Notice: Undefined property: stdClass::$StatusNET in /app/tasmoadmin/pages/devices_autoscan.php on line 61

Notice: Trying to get property of non-object in /app/tasmoadmin/pages/devices_autoscan.php on line 61

Notice: Undefined offset: 3 in /app/tasmoadmin/pages/devices_autoscan.php on line 62

**Comment by RaymondMouthaan** [comment] 2018-05-24 19:53
@aptonline I was not able to reproduce the errors ..

I just ran `docker run -it -p4444:80 -e APACHE_SERVER_NAME=mysyno.local --name tasmoadmin raymondmm/tasmoadmin` on my Synology NAS and did a device scan without issues.

![screen shot 2018-05-24 at 21 52 17](https://user-images.githubusercontent.com/25717738/40510375-c9a9abe6-5f9c-11e8-92ee-1707dc9017d2.png)

Do you have more info of what you did?

**Comment by aptonline** [comment] 2018-05-25 10:45
I’m using the GUI on Synology to create the container, but the settings are the same as your above command,  You can see the error in the attachment:
![37faf393-222e-486e-9db3-f0d7dd6dce3e](https://user-images.githubusercontent.com/190136/40540759-2466d1ca-6011-11e8-8d18-09581821579f.png)
![1c78d433-fa0b-4fd7-b99b-6438bc035ac2](https://user-images.githubusercontent.com/190136/40540760-24873d7a-6011-11e8-8dd0-8fd6cf4b1e51.png)

**Comment by RaymondMouthaan** [comment] 2018-05-25 10:54
Ill try deploying from DSM gui later today and hopefully reproduce your errors.

**Comment by aptonline** [comment] 2018-05-25 11:18
DSM 6.1
DS918+ ApolloLake (X64)

**Comment by RaymondMouthaan** [comment] 2018-05-25 11:20
Alright, good to know! This means you pull the same image as me. Thx

**Comment by aptonline** [comment] 2018-05-25 13:00
Just for reference I’m in the progress of upgrading to DSM 6.2... this could either fix it or break it more lol

**Comment by RaymondMouthaan** [comment] 2018-05-25 13:27
I'll try before and after dsm 6.2.

Btw have you used volume persistent for your container?

**Comment by aptonline** [comment] 2018-05-25 13:33
Yes /data is mapped to a folder on my synology, I can see the files/folders tasmoAdmin has created.

Updated to 6.2 ok, will test now.

**Comment by aptonline** [comment] 2018-05-25 13:34
Same issue here.

**Comment by RaymondMouthaan** [comment] 2018-05-25 18:33
@aptonline i've upgraded my syno DS1813+ to DSM6.2, deployed tasmoadmin via gui and did a device scan without any of those errors you are facing ...

Perhaps those errors are familiar to @reloxx13 ...

**Comment by aptonline** [comment] 2018-05-25 18:52
That’s strange, could you supply the exact settings/steps you used in the GUI so I can reproduce myself?

**Comment by RaymondMouthaan** [comment] 2018-05-25 19:15
Below every step i took to get it up and running ... one remark, in this case i didn't use volume!

Please first try out without volume and see if it makes any difference ...

![screen shot 2018-05-25 at 21 01 27](https://user-images.githubusercontent.com/25717738/40561969-88a04cae-605f-11e8-8b13-3d1c8145ee0e.png)

![screen shot 2018-05-25 at 21 01 39](https://user-images.githubusercontent.com/25717738/40561975-8d1b0bd4-605f-11e8-9c63-e641ec227cbb.png)

![screen shot 2018-05-25 at 21 02 01](https://user-images.githubusercontent.com/25717738/40561979-8ffbabd8-605f-11e8-8113-050dd9bda729.png)

![screen shot 2018-05-25 at 21 02 30](https://user-images.githubusercontent.com/25717738/40561982-92a7d140-605f-11e8-927b-f224b25d470d.png)

![screen shot 2018-05-25 at 21 02 52](https://user-images.githubusercontent.com/25717738/40561985-95013c7e-605f-11e8-9ae4-58153fd244cd.png)

![screen shot 2018-05-25 at 21 03 42](https://user-images.githubusercontent.com/25717738/40561990-97cbc71c-605f-11e8-9c9a-dda9380cbaa4.png)

![screen shot 2018-05-25 at 21 05 28](https://user-images.githubusercontent.com/25717738/40562003-9e357eb8-605f-11e8-96ed-2d4ff76770bc.png)

![screen shot 2018-05-25 at 21 05 55](https://user-images.githubusercontent.com/25717738/40562011-a2de3d92-605f-11e8-825c-6e5c9b55aca1.png)

![screen shot 2018-05-25 at 21 06 21](https://user-images.githubusercontent.com/25717738/40562019-a6d939ba-605f-11e8-8c5e-8d4187a32b05.png)

![screen shot 2018-05-25 at 21 11 00](https://user-images.githubusercontent.com/25717738/40562193-397e29a6-6060-11e8-9d28-d54f489d17bd.png)

![screen shot 2018-05-25 at 21 12 24](https://user-images.githubusercontent.com/25717738/40562229-60163590-6060-11e8-8b86-04232c344aa4.png)

**Comment by aptonline** [comment] 2018-05-25 19:44
Thanks for providing those step.

I’m sorry to say that I’ve received exactly the same error. Followed your steps to the letter. No volume used this time.

I’ve tried with using my domain name and the port and with just my local up and the port. Not specified password in the settings and used up range from 192.168.1.2 to 192.168.1.254

**Comment by RaymondMouthaan** [comment] 2018-05-25 19:49
Aah that's a pity 😔... I am out of options, hopefully @reloxx13 has some ideas, probably php related... 🤔

**Comment by aptonline** [comment] 2018-05-25 19:52
Thanks anyway.

**Comment by reloxx13** [comment] 2018-05-25 20:53
Duuuudes :D

Im busy with renaming, but it seems like one or more of your devices gives a wrong response.

Maybe its a missing WebLog Level2

On which Firmware Version and which Language are your devices? Their were a few JSON changes in the past which could also lead in such an error.

If you want to debug, go in the named file and add a var_dump

 /app/tasmoadmin/pages/devices_autoscan.php
between line 60 and 61
`var_dump($device);`

**Comment by reloxx13** [comment] 2018-05-25 20:54
Its not a server error, it found some devices but sth is wrong with the response.

**Comment by aptonline** [comment] 2018-05-25 21:16
@reloxx13 I’m running 	5.12.0 on the device in question.

Is there any other way to enable debug mode as I can’t get into the required file in my docker.

**Comment by RaymondMouthaan** [comment] 2018-05-25 21:26
I am running 5.14.0a and if i remember json's have indeed been changed somewhere in between.

@aptonline is it possible for you to update tasmota on one of your devices to 5.14.0? And then do the scan again for that ip address ?

If you want to edit files within your docker container, you need to install an editor like nano ...

Login to your container as root (don't know how to via gui), but from console:
```
$ docker exec -it --user root <container name>  /bin/sh
$ apk update && apk add nano
$ nano /app/tasmoadmin/pages/devices_autoscan.php
```

This should give you access to your container, install nano and edit the /app/tasmoadmin/pages/devices_autoscan.php file ..

**Comment by reloxx13** [comment] 2018-05-25 21:28
just a status 0 would help for now too of one of your devices, you can check yourself is a "StatusNET" key is in teh response.

**Comment by aptonline** [comment] 2018-05-25 21:43
Yeah I tried the Status 0 in the console of the device and can see StatusNet in the output.

**Comment by aptonline** [comment] 2018-05-25 21:55
@RaymondMouthaan btw OTA updates have never worked for me hence the interest in Tasmoadmin.  I’ve tried both local file and URL, they just fail.

**Comment by RaymondMouthaan** [comment] 2018-05-25 22:31
@aptonline can we close the issue, since the cause it known and the solution would be to update you devices to 5.14.0+ ?

**Comment by aptonline** [comment] 2018-05-26 05:18
I’ll attempt to update a device and test.  what about those users on <5.14.0 doesn’t this kinda defeat the whole point of tasmoadmin? Should it work with all firmware and allow to update them?

**Comment by RaymondMouthaan** [comment] 2018-05-26 12:18
l guess you have a valid point 🤔...

Did you succeed to update Tasmota on your devices?

**Comment by aptonline** [comment] 2018-05-26 13:53
Not yet, it usually fails each time and I have to re-flash via USB which is a pain.

**Comment by RaymondMouthaan** [comment] 2018-05-26 17:40
Glad to hear your flashing succeeded and works with TasmoAdmin!

It's up to @reloxx13 how to maintain compatible with previous versions. At least the ability to upgrade older versions to new but I am not sure how complex that might be... In this case it was just a matter of upper case, which it quite easy, but sometimes json structure change...

**Comment by reloxx13** [comment] 2018-05-26 18:48
pls provide a status 0.

it seems not to be a version problem, you corrected that indeed it is StatusNET.

**Comment by reloxx13** [comment] 2018-05-26 18:50
or do you remember that on 5.12 you used teh esp 2.4.0 library?

i think the most important json changes were on 5.9 or 5.11.

5.12 should work.

**Comment by kukudemajia** [comment] 2018-06-18 05:18
@reloxx13
the same problem.
Cause of the problem is:
Array ( [0] => ) stdClass Object ( [Host] => light_1-7231 [IP] => 192.168.0.103(tasmota 5.3)
stdClass Object ( [Hostname] => sonoff_energy_meter_sdm220-6116 [IPAddress] => 192.168.0.202(tasmota 6.0.0a)
in /home/lcc/TasmoAdmin/tasmoadmin/pages/devices_autoscan.php on line 61
$device->StatusNET->IPAddress  (For older firmware version should be $device->StatusNET->IP )
solution for me:
Tasmota firmware upgrade to 5.12.0 or newer

**Comment by reloxx13** [comment] 2018-06-25 20:42
@kukudemajia  thank you, ill catch this in next release.

**Closed by reloxx13** 2018-06-25 20:42 UTC
Labels: INVESTIGATE

**Comment by kukudemajia** [comment] 2018-06-26 01:02
cheers!

**Comment by sfeakes** [comment] 2018-11-27 15:06
I have the same problem.  All devices are on Tasmota 6.3.0 and tasmo-admin v1.6.1-beta1.

-- Here is the fix I made --
The sonoff search command is returning blanks in the array that causes this issue.
Editing devices_autoscan.php (Line 63) and adding a print statement to prove issue. 
```
 $devicesFound = $Sonoff->search( $urls );
print_r($devicesFound);
                        if( empty( $devicesFound ) ) {
```

Returns  (notice the first 4 elements).
1 device found
```
Array ( [0] => [1] => [2] => [3] => [4] => stdClass Object ( [Status] => stdClass Object ( [Module] => 1 [FriendlyName] => Array ( [0] => FrontDoorBell ) [Topic] => sonoff [ButtonTopic] => 0 [Power] => 0 [PowerOnState] => 3 [LedState] => 1 [SaveData] => 1 [SaveState] => 1 [SwitchTopic] => 0 [SwitchMode] => Array ( [0] => 0 [1] => 0 [2] => 0 [3] => 0 [4] => 0 [5] => 0 [6] => 0 [7] => 0 ) [ButtonRetain] => 0 [SwitchRetain] => 0 [SensorRetain] => 0 [PowerRetain] => 0 ) [StatusPRM] => stdClass Object ( [Baudrate] => 115200 [GroupTopic] => sonoffs [OtaUrl] => http://tiger/sonoff/firmware.bin [RestartReason] => Software/System restart [Uptime] => 0T14:11:18 [StartupUTC] => 2018-11-27T00:44:15 [Sleep] => 0 [BootCount] => 869 [SaveCount] => 2195 [SaveAddress] => FA000 ) [StatusFWR] => stdClass Object ( [Version] => 6.3.0 [BuildDateTime] => 2018-11-26T18:33:06 [Boot] => 6 [Core] => 2_3_0 [SDK] => 1.5.3(aec24ac9) ) [StatusLOG] => stdClass Object ( [SerialLog] => 2 [WebLog] => 2 [SysLog] => 0 [LogHost] => domus1 [LogPort] => 514 [SSId] => Array ( [0] => Feakes Lan [1] => ) [TelePeriod] => 300 [SetOption] => Array ( [0] => 54000009 [1] => 55818000 [2] => 00000001 ) ) [StatusMEM] => stdClass Object ( [ProgramSize] => 489 [Free] => 512 [Heap] => 18 [ProgramFlashSize] => 1024 [FlashSize] => 1024 [FlashMode] => 3 [Features] => Array ( [0] => 00000809 [1] => 0FDAE794 [2] => 240183A1 [3] => 23B617CE [4] => 00003BC0 ) ) [StatusNET] => stdClass Object ( [Hostname] => FrontDoorBell [IPAddress] => 192.168.144.70 [Gateway] => 192.168.144.1 [Subnetmask] => 255.255.255.0 [DNSServer] => 192.168.144.1 [Mac] => 68:C6:3A:8A:8C:51 [Webserver] => 2 [WifiConfig] => 3 ) [StatusMQT] => stdClass Object ( [MqttHost] => trident [MqttPort] => 1883 [MqttClientMask] => DVES_%06X [MqttClient] => DVES_8A8C51 [MqttUser] => DVES_USER [MqttType] => 1 [MAX_PACKET_SIZE] => 1000 [KEEPALIVE] => 15 ) [StatusTIM] => stdClass Object ( [UTC] => Tue Nov 27 14:55:33 2018 [Local] => Tue Nov 27 15:55:33 2018 [StartDST] => Sun Mar 25 02:00:00 2018 [EndDST] => Sun Oct 28 03:00:00 2018 [Timezone] => 1 [Sunrise] => 08:17 [Sunset] => 16:58 ) [StatusSNS] => stdClass Object ( [Time] => 2018-11-27T15:55:33 [Switch1] => ON ) [StatusSTS] => stdClass Object ( [Time] => 2018-11-27T15:55:33 [Uptime] => 0T14:11:18 [Vcc] => 3.162 [POWER1] => OFF [Wifi] => stdClass Object ( [AP] => 1 [SSId] => Feakes Lan [BSSId] => 78:8A:20:DD:73:2D [Channel] => 11 [RSSI] => 64 ) ) ) )
```
When no devices are found.
```
Array ( [0] => [1] => [2] => [3] => )
```

So editing devices_autoscan.php around line 65 to add a continue statement on blank array fixes the problem
```
foreach( $devicesFoundTmp as $device ) {
                                        if ( empty ($device) )
                                           continue;
                                        $ip                       = explode( ".", $device->StatusNET->IPAddress );
                                        $devicesFound[ $ip[ 3 ] ] = $device;
                                }

```

**Comment by RaymondMouthaan** [comment] 2018-11-27 15:34
@sfeakes, you might want to do a PR for your changes so @reloxx13 can review and accept those easily.
