### ISSUE TITLE
Unwanted underscore added

### ISSUE THREAD

**Issue by crispy78** [reloxx13/TasmoAdmin#210] opened 2018-09-04 21:35 UTC
I was fiddling around with TasmoAdmin (docker image) and when I changed my GroupTopic for all devices through the command line option to sonoff (GroupTopic sonoff) there was an underscore added so my GroupTopic became sonoff_
The same happened when I changed Topic to domoticz, it was changed to domoticz_
I’d prefer it wouldn’t add the underscore (unasked).

**Comment by reloxx13** [comment] 2018-09-05 17:42
not reproduceable

if the backlog says "domoticz", than this will be send to tasmota for 100%.
you can even open the console page of tasmota next to tasmoadmin and see the command.

![grafik](https://user-images.githubusercontent.com/14855001/45109628-62e50680-b140-11e8-97f8-a6997ad95f21.png)

what i found is, that the command will be send twice since backlog does not give any response, this will be fixed in next release. but still no underscore.

ill close this one and move conservation to the iphone issue.

**Comment by crispy78** [comment] 2018-09-05 19:18
You should give it a try through the command line option.

https://ibb.co/gq0dPe Is what I’ve sent through the command line, https://ibb.co/fcrDqK is what ended up in my device. Same goes for the Topic command.

**Comment by reloxx13** [comment] 2018-09-05 19:34
found it and fixed 👍

**Closed** 2018-09-05 19:37 UTC
Labels: BUG, DONE, FIXED
